<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ru.mail.polis.StartStopTest" tests="3" skipped="0" failures="0" errors="0" timestamp="2017-10-12T23:02:16" hostname="MacBook-Pro-Kostya.local" time="1.097">
  <properties/>
  <testcase name="create" classname="ru.mail.polis.StartStopTest" time="1.02"/>
  <testcase name="start" classname="ru.mail.polis.StartStopTest" time="0.004"/>
  <testcase name="stop" classname="ru.mail.polis.StartStopTest" time="0.071"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[окт. 13, 2017 2:02:17 ДП org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:36987: The target server failed to respond
окт. 13, 2017 2:02:17 ДП org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:36987
]]></system-err>
</testsuite>
